### ISSUE TITLE
Unable to locate Plex libraries

### ISSUE THREAD

**Issue by neogamerdrew** [LightDestory/PlexNFSWatchdog#2]
**Thank you in advance for the feedback!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help to respond as quickly as possible. To avoid duplicates, please search existing Issues before submitting one here.

### Description

Script is unable to locate my Plex libraries despite providing the correct path.

### Reproduction

neogamerdrew@redacted:~/Tools/plex-nfs-watchdog$ plex-nfs-watchdog/bin/plex-nfs-watchdog --scan --paths /mnt/unraid1/Movies /mnt/unraid1/TV\ Shows /mnt/unraid1/4K\ HDR\ Movies /mnt/unraid1/4K\ HDR\ TV\ Shows --host http://localhost:32400 --token redacted
INFO:   Found Plex configuration from cache: /home/neogamerdrew/.local/share/plex_nfs_watchdog_cache/plex_config.json
INFO:   Connected to Plex server
INFO:   Analyzing /mnt/unraid1/TV Shows
ERROR:  Could not find Plex section for /mnt/unraid1/TV Shows
INFO:   Analyzing /mnt/unraid1/Movies
ERROR:  Could not find Plex section for /mnt/unraid1/Movies
INFO:   Analyzing /mnt/unraid1/4K HDR TV Shows
ERROR:  Could not find Plex section for /mnt/unraid1/4K HDR TV Shows
INFO:   Analyzing /mnt/unraid1/4K HDR Movies
ERROR:  Could not find Plex section for /mnt/unraid1/4K HDR Movies

neogamerdrew@redacted:~/Tools/plex-nfs-watchdog$ ll /mnt/unraid1
total 88
drwxrwxrwx 1           99 users    67 Jul 14 20:21  ./
drwxr-xr-x 3 root         root   4096 Jun 22 05:40  ../
drwxrwxr-x 1           99 users    44 May 30 03:56 '4K HDR Movies'/
drwxrwxr-x 1           99 users    94 Apr 21 00:54 '4K HDR TV Shows'/
drwxrwxrwx 1           99 users 61440 Jul 14 19:30  Movies/
drwx------ 1           99 users    31 Apr 21 00:55  .Trash-1000/
drwxrwxrwx 1           99 users  8192 Jul 12 03:42 'TV Shows'/

### Environment

Ubuntu latest
Running script in python venv
Libraries are mounted NFS share

**Comment by LightDestory** [comment]
Please provide the absolute path for your local storage versus the netowrk storage.

I think that there is a mismatch between these paths

**Comment by neogamerdrew** [comment]
I'm not sure I understand. The path provided is the folder the network storage is mounted to. What format are you suggesting?

**Comment by LightDestory** [comment]
The error you are facing is generated here https://github.com/LightDestory/PlexNFSWatchdog/blob/master/src/plex_nfs_watchdog/modules/plex/plex_agent.py#L214

When you give a path, it looks up the parents until a library is found. You were trying to scan directly a Plex Section... It was not supported by the command `--scan`.

With the newest update it is now allowed.

If you want to keep a service on the background you must use the `-d` command!

Try the latest version and let me know.

**Comment by neogamerdrew** [comment]
Your update did indeed fix it. Sorry, didn't understand I was supposed to provide the parent folder of the library sections.  Apprecaite the help!
